name: flutter_keyboard_visibility_platform_interface
publish_to: none
description: A common platform interface for the flutter_keyboard_visibility plugin.
version: 2.0.0
homepage: https://github.com/MisterJimson/flutter_keyboard_visibility
repository: https://github.com/MisterJimson/flutter_keyboard_visibility

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ">=1.16.0 <2.0.0"
  plugin_platform_interface: 
    git: https://github.com/kumsumit/plugin_platform_interface.git

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter